// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doekfktuqcadrlnvcprk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZWtma3R1cWNhZHJsbnZjcHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODIzOTQsImV4cCI6MjA2NjM1ODM5NH0.OOufftP7WRaoaOal7RYXrxjsIGMK-FFhltxDvK2sHIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);